### ISSUE TITLE
Consider using pygit2 for Git interface

### ISSUE THREAD

**Issue by josemanimala** [mobiusbyte/bumpit#29]
**Is your feature request related to a problem? Please describe.**
Possibly, when used with a brand new jenkins machine git config --user.* is not setup correctly. 
Pygit2 provides a cleaner interface to running git commands.

**Describe the solution you'd like**
bumpit.yaml
```
user:
  name: username
  email: email@example.com
```
Code sample:
```
import pygit2 
tagger = pygit2.Signature('Bumpit Bot', 'bumpit@example.com')
repo.create_tag(name="version", repo.head.tatget.hex ,pygit2.GIT_OBJ_BLOB, tagger, "Next release")
```
References:
https://github.com/libgit2/pygit2/blob/5b015f7008c4c3079d72e948669bcd3964c00633/test/test_tag.py#L58

Edits
Added more details to examples and code sample in pygit2

**Comment by mobiusbyte** [comment]
@josemanimala , thanks for the feedback.

I have fixed this issue in https://pypi.org/project/bumpit/0.6.0/.

I have opted to not use `pygit` because the code I added to address this issue is simple enough and `git` cli is stable that it didn't seem like a compelling idea to add in a 3rd party wrapper for git. On top of this, I scanned the issue backlog for `pygit` and it wasn't looking too great. 

So since `bumpit` relies on minimal git features and the code that does all these interactions are pretty self contained in `vcs.py`, I think this is clean enough segregation of concerns.
